name: Generated IPA (Upload)

env:
  # The name of the main module repository
  main_project_module: YourProjectName.xcodeproj

  # The name of the App Store
  appstore_name: Your App Store

on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
      # Install Xcode and other dependencies
      - name: Install Xcode and other dependencies
        run: |
          sudo gem install cocoapods
          sudo xcode-select --switch /Applications/Xcode_13.app
          pod install

      # Run Build Project
      - name: Build Xcode project
        run: xcodebuild -project ${{ env.main_project_module }} -scheme YourSchemeName -configuration Release archive -archivePath ${{ env.main_project_module }}/build/YourApp

      # Export IPA Release
      - name: Export IPA release
        run: xcodebuild -exportArchive -archivePath ${{ env.main_project_module }}/build/YourApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ${{ env.main_project_module }}/build/outputs/ipa

      # Upload Artifact Build
      - name: Upload IPA Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.date_today }} - ${{ env.appstore_name }} - ${{ env.repository_name }} - IPA(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/ipa/
