name: Generated IPA (Upload)

env:
  # The name of the main module repository
  main_project_module: Login App

  # The name of the App Store
  appstore_name: Frogobox ID

on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # Install Xcode CLI tools
      - name: Install Xcode CLI tools
        run: xcode-select --install || true

      # Set Up Ruby
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # Install fastlane
      - name: Install fastlane
        run: gem install fastlane -NV

      # Run fastlane
      - name: Run fastlane
        run: fastlane release

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload IPA - ${{ env.repository_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.date_today }} - ${{ env.appstore_name }} - ${{ env.repository_name }} - IPA generated
          path: ${{ env.main_project_module }}/build/outputs/MyApp.ipa
