name: iOS Build Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    env:
      WORKSPACE: YourWorkspace.xcworkspace
      SCHEME: YourScheme
      SIMULATOR: "platform=iOS Simulator,name=iPhone 12 Pro,OS=15.3"
    steps:
      - uses: actions/checkout@v2
      - name: Install Xcode
        uses: github/actions/setup-xcode@v2
        with:
          version: '13.2.1'
      - name: Install Dependencies
        run: |
          if [ -e Podfile ]; then
            gem install bundler
            bundle install
            pod install
          else
            echo "No Podfile found, skipping dependency installation."
          fi
      - name: Build
        run: |
          xcodebuild clean build \
            -workspace $WORKSPACE \
            -scheme $SCHEME \
            -sdk iphonesimulator \
            -destination "$SIMULATOR"
