name: iOS CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: macOS-latest
    env:
      WORKSPACE: YourWorkspace.xcworkspace
      SCHEME: YourScheme
      SIMULATOR: "platform=iOS Simulator,name=iPhone 12 Pro,OS=15.3"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          pod install
      - name: Build
        run: |
          xcodebuild clean build \
            -workspace $WORKSPACE \
            -scheme $SCHEME \
            -sdk iphonesimulator \
            -destination "$SIMULATOR"
      - name: Run Tests
        run: |
          xcodebuild test \
            -workspace $WORKSPACE \
            -scheme $SCHEME \
            -sdk iphonesimulator \
            -destination "$SIMULATOR"
