name: CICD Demo
on:
  push:
    branches:
      - ${{ env.BRANCH_NAME }}
  pull_request:
    branches:
      - ${{ env.BRANCH_NAME }}
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo Xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Build & Test
        run: xcodebuild clean build test -workspace ${{ env.WORKSPACE_NAME }} -scheme ${{ env.SCHEME_NAME }} -destination '${{ env.SIMULATOR_DESTINATION }}'
    env:
      WORKSPACE_NAME: ProjectName.xcworkspace
      SCHEME_NAME: SchemeName
      SIMULATOR_DESTINATION: 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.2'
